from typing import Protocol
from datetime import datetime


class BrokerReadAdapter(Protocol):
    """Read capability only. Order submission is a separate future interface."""
    def accounts(self) -> list[dict]: ...
    def instruments(self) -> list[dict]: ...
    def prices(self, instrument_ids: list[str]) -> list[dict]: ...
    def candles(self, instrument_id: str, start: datetime, end: datetime) -> list[dict]: ...
    def trading_status(self, instrument_id: str) -> dict: ...
    def portfolio(self, account_id: str) -> dict: ...
    def positions(self, account_id: str) -> dict: ...
    def orders(self, account_id: str) -> list[dict]: ...
